# Start with a base image that includes Go
FROM golang:1.20 AS build

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o notification-ingestor ./producer

# FROM ubuntu:22.04

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    libssl-dev \
    build-essential

# Expose port 8080 to the outside world
EXPOSE 80

# Command to run the executable
CMD ["/app/notification-ingestor"]
