apiVersion: v1
kind: Service
metadata:
  name: notification-consumer
spec:
  selector:
    app: notification-ingestor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Change to NodePort if LoadBalancer is not supported