apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-ingestor
  template:
    metadata:
      labels:
        app: notification-ingestor
    spec:
      containers:
      - name: notification-container
        image: notification-ingestor:latest  # Replace with your Docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"  # Kafka service name and port
        - name: KAFKA_CLIENT_PASSWORDS
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords   # The name of the Kubernetes secret
              key: client-passwords        # The specific key within the secret- name: SECRET_USERNAME    
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
